config/routes.rb
Rails.application.routes.draw do

  resources :utensilnames
  resources :depriciation_categories
  resources :departments
  root :to => "kitchen_users#login"
  get 'vesselplanners/dispatched'
  post 'vesselplanners/dispatched' 
  get 'vesselplanners/dropdown1'
  get 'vesselplanners/vessel_dispatch'
  post 'vesselplanners/vessel'
  get 'vesselplanners/vessel'
  get 'vesselplanners/new1'
  post 'vesselplanners/new1'
  post 'vesselplanners/new'
  get 'vesselplanners/new'
  get 'vesselplanners/dropdown'
  get 'vesselplanners/index1'
  post 'vesselplanners/index1'

  post 'feedback_report' => 'feedbacks#feedback_report'

  get 'utensils/fetch_utensil_category'

  get 'vesselplanners/index'
  get 'vesselplanners/details'
  get 'vesselplanners/utensilname'
  post 'vesselplanners/create'
  post 'vesselplanners/delete'
  get 'vesselplanners/tenantdetails'
  post 'vesselplanners/assigned_vessel'
  get  'vesselplanners/assigned_vessel'
  get 'vesselplanners/vessel_tenantdetail'
  get 'vesselplanners/edit'
  patch 'vesselplanners/update'



 # post 'vesselplanners/new'
  post 'audit_report' => 'auditreviews#audit_report'  

  get 'tenants/user_feedback'

  post 'menu_masters/menumaster_report'

  post 'menu_customers/csv_sheet'

  get 'daily_cook_sheet' => 'menu_customers#daily_cook_sheet'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  post 'feedbacks/feedback_update'
 
  post 'enrolments/enrol_delete_approval'

  post 'enrolments/newenrol_approval'

  get 'enrolments/approval_screen'

  post 'feedbacks/approval_feedback'
 
  get 'food_returns_report' => 'feedbacks#food_returns_report'

  post 'food_returns_report' => 'feedbacks#food_returns_report'

  get 'delivery_report' => 'dispatches#delivery_report'
  post 'delivery_report' => 'dispatches#delivery_report'

  get 'utensil_report' => 'utensils#utensil_report'
  #post 'utensil_report' => 'utensils#utensil_report'

  get 'customer_report' => 'tenants#customer_report'
  post 'customer_report' => 'tenants#customer_report'  

  get 'enrol_index' => 'enrolments#enrol_index'
  
  get 'attendance_index' => 'enrolments#attendance_index'
  get 'attendance' => 'enrolments#attendance'

  get 'point_of_sales/get_restriction'

  get 'kitchens/check_facilit_present'
  post 'kitchens/check_facilit_present'

  get 'tenant/check_meal_info'
  post 'tenant/check_meal_info'

  get 'point_of_sales/get_data'

  get 'point_of_sales/check_date'
  post 'point_of_sales/check_date'

  get 'meal_courses/check_position'
  post 'meal_courses/check_position'    

  get 'point_of_sales/check_tenant'
  post 'point_of_sales/check_tenant'

  get '/edit_item' => 'production_items#edit_item'
  patch '/update_item' => 'production_items#update_item'

  get 'unit_of_measurements/bck'

  get 'tenants/check_mg_present'
  post 'tenants/check_mg_present'

  get 'normalmenu_sites/menu_assign'

  get 'normalmenu_sites/menuplanner_design'

  get 'normalmenu_sites/menu_planner'

  get 'normalmenu_sites/wastage'
  post 'normalmenu_sites/wastage'

  get "kitchen_users/dynamic_drop"
  #post "kitchen_users/dynamic_drop"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get"check_tet/normalmenu_sites"
  post"check_tet/normalmenu_sites"
  get "kitchen_users/login"
  post "kitchen_users/login_validation"
  get 'kitchen_users/logout'
  get "kitchens/index"
  post "kitchens/create"
  get "kitchens/chef"

  get "food_groups/image_pop"
  get "customer_view_controls/billing_pop"
  get "customer_view_controls/nutrition_pop"
  get "/status" =>"normalmenu_sites#order_status"
  post "/status" =>"normalmenu_sites#order_status"
  get "/summaries" =>"normalmenu_sites#summary"
  post "/summaries" =>"normalmenu_sites#summary"
  get "/enrolled" =>"normalmenu_sites#enrolled"
  post "/enrolled" =>"normalmenu_sites#enrolled"
  get "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  post "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  get "/delivery_status" =>"normalmenu_sites#delivery_status"
  post "/delivery_status" =>"normalmenu_sites#delivery_status"

  get "normalmenu_sites/delivery_problem_status"
  post "normalmenu_sites/delivery_problem_status"

  get "/utensil_status" =>"normalmenu_sites#utensil_status"
  post "/utensil_status" =>"normalmenu_sites#utensil_status"
  get "enrolments/enrolment_upload"
  post "enrolments/enrolment_upload"
  get "enrolments/upload_process"
  post "enrolments/upload_process"
  get "normalmenu_sites/dashboard"
  post "normalmenu_sites/dashboard"
  get "normalmenu_sites/summary_edit"
  post "normalmenu_sites/summary_edit"
  get "normalmenu_sites/drop"
  get "normalmenu_sites/dropdown1"

  get "normalmenu_sites/normalmenu_category_add"
  #post "normalmenu_sites/normalmenu_category_add"
  post "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenu_category_edit"
  #post "normalmenu_sites/normalmenu_category_edit"
  post "normalmenu_sites/normalmenu_category_edit_save"
  get "normalmenu_sites/normalmenu_category_show"
  get "normalmenu_sites/normalmenu_category_delete"
  #post "normalmenu_sites/normalmenu_category_delete"
  get "normalmenu_sites/notreceive_status"

  get "enrolments/individual"

  get "feedbacks/allow_update"
  post "feedbacks/allow_update"

  get 'software_setups/check_username_present'
  post 'software_setups/check_username_present'

  get 'dispatch_utensils_mappings/rec'
  post 'dispatch_utensils_mappings/rec'

  resources :standards
  resources :item_meal_restrictions
  resources :menu_customers
  resources :menu_production_items
  resources :menu_masters
  resources :meal_restrictions
  resources :item_meal_courses
  resources :meal_courses
  resources :auditreviews
  resources :feedbacks
  resources :point_of_sales
  resources :kitchens
  resources :customer_view_controls
  resources :parent_orders
  resources :software_setups
  resources :dispatch_utensils_mappings
  resources :utensils_count_mappings
  resources :utensils_categories
  resources :payments
  resources :normalmenu_sites
  resources :normal_menus
  resources :operations
  resources :production_items
  resources :production_categories
  resources :item_subcategories
  resources :unit_of_measurements
  resources :nutritions
  resources :software_setup
  resources :food_groups
  resources :food_categories
  resources :item_categories
  resources :categories
  resources :tenants
  resources :dispatches
  resources :utensils
  resources :site_categories
  resources :enrolments
  resources :page_configurations
  resources :pages
  resources :tenant_details
  resources :users
  resources :kitchen_users
  resources :alleries
  
end

app/models/point_of_sale.rb
class PointOfSale < ApplicationRecord

  belongs_to :tenant
  belongs_to :food_category
  belongs_to :meal_restriction, optional: true
  validates :date, :meal_time, :quantity, presence: true
  acts_as_paranoid

  def self.pointofsale(params)
    pointofsale = []
    #user = User.find(params[:user_id])
    if params[:type] == "tenant"
      tn = Tenant.find(params[:tenant_id])
      fromdate = Date.commercial(Date.today.year, -1+Date.today.cweek, 1)
      todate = Date.today
      id = PointOfSale.where(date: fromdate .. todate).where(tenant_id: tn).ids
      pointofsale = { :tenant => tn.name, :pos_menu => PointOfSale.where(id: id).map{|pp| {:id => pp.id, :date => pp.date, :meal_time => pp.meal_time, :meal_type => pp.meal_type, :meal_category => pp.meal_category, :quantity => pp.quantity, :comment => pp.comment, :actual_qty => pp.actual_qty, :flag => pp.flag, :time => [pp.time.split("|").first.to_date.strftime("%d-%m-%y"),pp.time.split("|").last].join(" "), :updated_at => pp.updated_at.strftime("%a %b %e %Y %I:%M %p") }}}
    else params[:type]  == "admin"
      fromdate = Date.commercial(Date.today.year, -1+Date.today.cweek, 1)
      todate = Date.commercial(Date.today.year, +1+Date.today.cweek, 1)
      id = PointOfSale.where(date: fromdate .. todate).ids
      pointofsale = { :tenant => Tenant.pluck(:id, :name), :pos_menu => PointOfSale.where(id: id).map{|pp| {:id => pp.id, :date => pp.date, :tenant => pp.tenant.name, :meal_time => pp.meal_time, :meal_type => pp.meal_type, :meal_category => pp.meal_category, :quantity => pp.quantity, :comment => pp.comment, :actual_qty => pp.actual_qty, :flag => pp.flag, :time => [pp.time.split(" ").first.to_date.strftime("%d-%m-%y"),pp.time.split("|").last].join("|"), :updated_at => pp.updated_at.strftime("%a %b %e %Y %I:%M %p")}}}
    end
    return pointofsale

  end

    def self.export
    
        columns=[ "date", "tenant", "meal_time", "role_id", "subscription_type", "meal_type", "meal_category", "quantity", "actual_qty", "amount_paid", "comment","flag","time"]
    
        CSV.open("#{Rails.root}/public/files/Dailyorderexport.csv",'w') do |csv|
    
            csv << columns.map{|aa|aa.humanize}
     
            all.each do |product|
     
                mm=product.attributes.values_at(*columns)
       
                mm[1]=product.tenant.name
       
                csv << mm
        
            end
            
        end

    end

end

app/controllers/point_of_sales_controller.rb
class PointOfSalesController < ApplicationController
  before_action :set_point_of_sale, only: [:show, :edit, :update, :destroy]

  # GET /point_of_sales
  # GET /point_of_sales.json
  def index
    @point_of_sales = PointOfSale.all.order('created_at DESC')
  end

  # GET /point_of_sales/1
  # GET /point_of_sales/1.json
  def show
    
  end

  # GET /point_of_sales/new
  def new    
    #params[:point_of_sale][:food_category_id] = FoodCategory.find_by(:name=> params[:point_of_sale][:food_category_id]).id
    @point_of_sale = PointOfSale.new
    @tenants = Tenant.where(:active => true)
    if params[:commit].present?
      @point_of_sale = PointOfSale.new(point_of_sale_params)
      @point_of_sale.food_category_id = FoodCategory.find_by('lower(name) =? ', "veg").id
      if @point_of_sale.save
        menu_customer_packs = MenuCustomer.find_by(date: @point_of_sale.date, tenant_id: @point_of_sale.tenant_id, meal_restriction_id: @point_of_sale.meal_restriction_id, category_id: Category.find_by(:category_name=>@point_of_sale.meal_time).id, stud_type: @point_of_sale.stud_type)
        if menu_customer_packs.present?
            count_to_update = menu_customer_packs.packs_to_send.to_i + @point_of_sale.quantity
            menu_customer_packs.update(:packs_to_send=>count_to_update)
        end
        redirect_to point_of_sales_path
      else
        redirect_to point_of_sales_path
      end
    end
    #if params[:tenant_id].present?
    #  @tenant_details = Tenant.find(params[:tenant_id]).tenant_details
    #end
  end

  def get_data
    #@tenant_id = Tenant.find(params[:format].to_i)
    @point_of_sale = PointOfSale.new
    @tenant_details = Tenant.find(params[:format].to_i).tenant_details
    @meal_restriction = []
    #redirect_to :action=>"new",:tenant_id=>@tenant_id
  end

  # GET /point_of_sales/1/edit
  def edit
   
  end

  # POST /point_of_sales
  # POST /point_of_sales.json
  def create
    respond_to do |format|
      if @point_of_sale.save
        menu_customer_packs = MenuCustomer.where(date: @point_of_sale.date,tenant_id: @point_of_sale.tenant_id).find_by(category_id: Category.find_by(:category_name=>@point_of_sale.meal_time).id)
        if menu_customer_packs.present?
            count_to_update = menu_customer_packs.packs_to_send.to_i + @point_of_sale.quantity
            menu_customer_packs.update(:packs_to_send=>count_to_update)
        end
         
        format.html { redirect_to point_of_sales_path, notice: 'Point of sale was successfully created.' }
        format.json { render :show, status: :created, location: @point_of_sale_path }
      else
        format.html { render :new }
        format.json { render json: @point_of_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_of_sales/1
  # PATCH/PUT /point_of_sales/1.json
  def update
  
    #params[:point_of_sale][:food_category_id] = FoodCategory.find_by(:id=> params[:point_of_sale][:food_category_id]).name
    #params[:point_of_sale][:food_category_id] = FoodCategory.find_by(:name=> params[:point_of_sale][:food_category_id]).id
    respond_to do |format|
      if @point_of_sale.update(point_of_sale_params)
        format.html { redirect_to point_of_sales_path, notice: 'Point of sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @point_of_sale }
      else
        format.html { render :edit }
        format.json { render json: @point_of_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_of_sales/1
  # DELETE /point_of_sales/1.json
  def destroy

    @point_of_sale.destroy
    respond_to do |format|
      format.html { redirect_to point_of_sales_url, notice: 'Point of sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_tenant

    #@meal_time = Tenant.find_by(:id=>params[:tenant]).tenant_details.map{|i| Category.find_by(:category_name=>i.meal_time).id}
    @meal_time = TenantDetail.where(:tenant_id=> params[:tenant]).pluck(:meal_time)
    @foodcat_name = TenantDetail.where(:tenant_id=> params[:tenant]).map{|i| i.food_category.name}.uniq
    @fdate = Tenant.find_by(:id=> params[:tenant]).from_date
   
    @tdate = Tenant.find_by(:id=> params[:tenant]).to_date

    #@foodcat_name = TenantDetail.where(:tenant_id=> params[:tenant]).map{|i| i.id}
  end

   def check_date

    #@meal_time = Tenant.find_by(:id=>params[:tenant]).tenant_details.map{|i| Category.find_by(:category_name=>i.meal_time).id}
    @fdates = Tenant.where(id: params[:tenant]).pluck(:from_date, :to_date)
    #@tdates = Tenant.where(id: params[:tenant]).pluck(:to_date)
    render json: {"message"=> @fdates}  
    #render json: {"messagee"=>  @tdates}
  end

  def get_restriction
    meal_restrictions = Tenant.find(params[:tenant_id]).tenant_details.where(:meal_time => params[:meal_time]).pluck(:meal_restriction_id).compact
    @meal_restriction = MealRestriction.where(id: meal_restrictions)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_of_sale
      @point_of_sale = PointOfSale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_of_sale_params
      params.require(:point_of_sale).permit(:date, :tenant_id, :meal_time, :meal_restriction_id, :quantity, :food_category_id, :comment, :stud_type)
      #params.permit(:point_of_sale)
    end
end

app/helpers/point_of_sales_helper.rb
module PointOfSalesHelper
end

app/views/point_of_sales/_pos_partial.html.erb
<article class="content item-editor-page" id="ten_detail">
  <div class="title-block">        
  <h4 class="title"> <span class="sparkline bar" data-type="bar"></span> </h4>
  </div>
  <form name="item">
  <div class="card card-block">
    <div class="row">
      <div class="form-group">
        <%= form_for @point_of_sale,:url => {:controller => "point_of_sales", :action => "create"} do |f| %>

          <div class="col-xs-4" >
            <label class="control-label"><%= f.label :stud_type %></label>
            <div class="form-group">
              <%= f.select :stud_type, ['Primary','Secondary'], {prompt: true }, {class: "form-control boxed e1 a2", id: "student_type"}%>
            </div>
          </div>          

          <div class="col-xs-4" >
            <label class="control-label"><%= f.label :meal_time %></label>
            <div class="form-group">
              <%= f.collection_select :meal_time, Category.where(:category_name => @tenant_details.pluck(:meal_time)).order(:category_name), :category_name, :category_name, {:prompt => true}, {class: "form-control e1", id: "mt" } %>
            </div>
          </div>


          <div class="col-xs-4" >
            <label class="control-label"><%= f.label :meal_restriction_id %></label>
            <div class="form-group">
              <%= f.collection_select :meal_restriction_id, @meal_restriction, :id, :meal_restriction_name, {:prompt => "select"}, {class: "form-control e1 meal_restriction" } %>
              </div>
          </div>


          <div class="col-xs-4">
            <label class="control-label"><%= f.label :Date %></label>
            <div class="form-group">
              <%= f.text_field :date, :id => "txtFrom", class: "form-control boxed", required: true, :readonly=> true %>
            </div>
          </div> 
          
          <div class="col-xs-4">
            <label class="control-label"><%= f.label :quantity %></label>
            <div class="form-group">
              <%= f.text_field :quantity, :class=>"form-control", :required=>"true" %>
            </div>
          </div>

          <!-- <div class="col-xs-4 http">
            <label class="control-label"><%#= f.label :food_category_id %></label>
            <div class="form-group">
              <%#= f.collection_select :food_category_id, FoodCategory.where(:id => @tenant_details.pluck(:food_category_id).uniq).order(:name), :id, :name, {:prompt=>true}, {class: "form-control e1"} %>
            </div>
          </div> -->

          <div class="col-xs-4">
            <label class="control-label"><%= f.label :comment %></label>
            <div class="form-group">
              <%= f.text_field :comment,:class=>"form-control" %>
            </div>
          </div>

          <%= f.hidden_field :tenant_id, value: @tenant_details.first.tenant_id %>

          <div class="form-group row mrgn-top">
            <div class="col-sm-10 col-sm-offset-2">
              <%= f.submit "Submit", :class=>"btn btn-primary" %>
            </div>
          </div>

        <% end %>

      </div>
    </div>
  </div>
  </form>
</article>

<% to_date = @tenant_details.first.tenant.to_date %>

<script type="text/javascript">
  $(function(){
  	  var today = new Date();  
      $("#txtFrom").datepicker({      	
    	dateFormat: 'yy-mm-dd', 
    	minDate: today,
    	maxDate: '<%= to_date %>',
        autoclose: true, 
        todayHighlight: true
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function () {
    $("#mt").change(function () {
      var meal_time=($(this).val());
      $.ajax({
        type: "GET",
        url: "/point_of_sales/get_restriction?meal_time="+meal_time+"&tenant_id="+"<%= @tenant_details.first.tenant_id %>"
      })
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function () {
    $(".e1").select2();
  });            
</script>

app/views/point_of_sales/check_tenant.js.erb

<% if @meal_time %>

 $('.meal_time').html("<%= escape_javascript(options_for_select(@meal_time)) %>");
 $('.foodcat').html("<%= escape_javascript(options_for_select(@foodcat_name)) %>");
 $('#f').html("<%= escape_javascript @fdate.to_s %>");
 $('#t').html("<%= escape_javascript @tdate.to_s %>");
<% end %>

app/views/point_of_sales/get_data.js.erb
$("#ten_detail").html("<%= escape_javascript(render 'pos_partial') %>");

app/views/point_of_sales/get_restriction.js.erb
//	$('.meal_restriction').html("<%= escape_javascript(options_from_collection_for_select(@meal_restriction, :id, :meal_restriction_name))%>");



$('.meal_restriction').html("<%= escape_javascript select("meal_restriction_id", "id", @meal_restriction.collect {|p| [ p["meal_restriction_name"], p["id"] ] },{:include_blank => "Please select"}, {class: "meal_restriction"})%>");

app/views/point_of_sales/index.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container">
    <div class="body-header">
      <h3>Meal Order <span> <%= link_to 'New Meal Order',new_point_of_sale_path,:class=>"btn btn-primary btn-sm rounded-s"%></span></h3>
      <!-- <h2>Item List</h2> -->
    </div>
    <div class="body-content">
      <div id="dashboard-container">
        <div class="table-container">
           <table class="table table-striped table-bordered table-hover display" cellspacing="0" width="100%"  id="point_of_sale">
           <thead>
                 <tr>
                    <th>Customer</th>
                    <th>Date</th>
                    <th>Meal Time</th>
                    <th>Restriction</th>
                    <th>Quantity</th>
                    <!-- <th>Meal Type</th> -->
                    <th>Comment</th>  
                  </tr>
                </thead>
                <tbody>
               <% @point_of_sales.each do |point_of_sale| %>
               
                  <tr id="<%=point_of_sale.id%>">
                  <td><%=point_of_sale.tenant.name%></td>
                  <td><%= format_date(point_of_sale.date) %></td>      
                  <td><%= point_of_sale.meal_time %></td>
                  <td><%= point_of_sale.meal_restriction.present? ? point_of_sale.meal_restriction.meal_restriction_name : nil %></td>
                  <td><%= point_of_sale.quantity%></td>
                  <!-- <td><%#= point_of_sale.food_category.name%></td> -->
                  <td><%= point_of_sale.comment%></td>
                  
                 <!--  <td><!%=link_to "",production_item, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-sm btn-default fa fa-sm fa-trash-o" ,:style=>"color:red"%></td> -->
                  </tr>
        
           <%end%>
           </tbody>            
          </table>
           <div class="side-pop" style="color:white;display:none;">
    <ul>
    <li><a title="Show" id="show" > <i class="btn btn-sm btn-default fa fa-sm fa-eye"></i></a></li>
      <li><a title="Edit" id="edit" > <i class="btn btn-sm btn-default fa fa-sm fa-pencil" ></i></a></li>
     <%if CEO? %>
    <li><a title="Delete" id="destroy" data-method="delete" class="confirmation"> <i class="btn btn-sm btn-default fa fa-sm fa-trash-o"></i></a></li>
    <%end%> 
           </ul>
    </div>  
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
  <script>
  $('.confirmation').on('click', function () {
        return confirm('Are you sure?');
    });
</script>

app/views/point_of_sales/new.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container ">  
	<div class="body-header">
      <h3 class="modal-title">Add - Meal Order</h3>
  	</div>
    <%#= render 'form', point_of_sale: @point_of_sale %>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>

    <article class="content item-editor-page">      
      <div class="title-block">        
        <h4 class="title"> <span class="sparkline bar" data-type="bar"></span> </h4>
      </div>
      <form name="item">
        <div class="card card-block">
          <div class="row">
            <div class="form-group">
              <div class="col-xs-4">
                <label class="control-label">Tenant</label>
                <div class="form-group">
                  <%#= f.collection_select :tenant_id, Tenant.order(:name),:id,:name,{:prompt=>true} ,{class: "form-control tenant", :id=> "demo"}%>
                  <%= select_tag 'tenant_id', options_from_collection_for_select(@tenants.order(:name), :id, :name), :id => "fold", :class => "e1", :include_blank => "-Select-" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>  
    </article>

    <div id="ten_detail">
      <% if @tenant_details.present? %>
      
        <%= render 'pos_partial' %>
       
      <% end %>
    </div>

  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $("#fold").change(function () {
      var id=($(this).val());
      $.ajax({
        type: "GET",
        url: "/point_of_sales/get_data."+id
      })
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function () {
    $(".e1").select2();
  });            
</script>

app/views/point_of_sales/show.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container">  
  <div class="body-header">
     <center><h3 class="modal-title">Show - Meal order</h3></center>

   </div>    
          <article class="content item-editor-page">
        
            <div class="card card-block">
  
              <div class="row">
      
                <div class="form-group">
        
                  <div class="col-xs-4">
            
                    <label class="control-label"><span style="font-weight:bold">Date</span></label>
                
                    <div class="form-group"><%= @point_of_sale.date %></div>
                
                  </div>
            
                  <!-- <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Quantity</span></label>
      
                    <div class="form-group"><!%= @nutrition.quantity %></div>
                
                  </div> -->

                  <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Customer</span></label>
   
                    <div class="form-group"><%=@point_of_sale.tenant.present? ? @point_of_sale.tenant.name : nil %></div>
                
                  </div>
<!-- 
                  <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Cost</span></label>
      
                    <div class="form-group"><%#= @menu_master.cost %></div>
                
                  </div> -->

                  <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Meal_time:</span></label>
      
                    <div class="form-group"><%= @point_of_sale.meal_time %></div>
                
                  </div>
               

                  <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Meal_Restriction:</span></label>
      
                    <div class="form-group"><%= @point_of_sale.meal_restriction.present? ? @point_of_sale.meal_restriction.meal_restriction_name : nil%></div>
                
                  </div>


                  <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Quantity</span></label>
      
                    <div class="form-group"><%= @point_of_sale.quantity.present? ? @point_of_sale.quantity : nil %></div>
                
                  </div>



                   <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Food_category</span></label>
      
                    <div class="form-group"> <%= @point_of_sale.food_category.present? ? @point_of_sale.food_category.name:
                    nil %></div>
                
                  </div>
                  

                  
                  

                  
                  <!-- <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">UOM</span></label>
      
                    <div class="form-group"><!%= @nutrition.unit_of_measurement.name%></div>
                
                  </div> -->

      


                  <div class="col-xs-4">
  
                    <label class="control-label"><span style="font-weight:bold">Comment</span></label>
      
                    <div class="form-group"> <%= @point_of_sale.comment.present? ? @point_of_sale.comment :
                    nil %></div>
                
                  </div>
<!-- 
                 <div class="col-xs-4">
                  <label class="control-label"><span style="font-weight:bold">Updated_by</span></label> 
                  <div class="form-group">
                     <%#= @menu_customer.updated_by %>
                  </div>
                </div>
  -->                 
                </div>
        
              </div>  
        
            </div>
      
          </article>
  
         
    <div class="footer">
  
     <%= link_to 'Back', point_of_sales_path, :class=>"btn btn-default"%>  
      <!--%= link_to 'Edit', edit_nutrition_path(@nutrition), :class=>"btn btn-primary"%-->
  
   
    </div>
  
  </div>

</div>






























<!-- <p id="notice"><%= notice %></p>

<%#= link_to 'Edit', edit_point_of_sale_path(@point_of_sale) %> |
<%#= link_to 'Back', point_of_sales_path %> -->