config/routes.rb
Rails.application.routes.draw do

  resources :utensilnames
  resources :depriciation_categories
  resources :departments
  root :to => "kitchen_users#login"
  get 'vesselplanners/dispatched'
  post 'vesselplanners/dispatched' 
  get 'vesselplanners/dropdown1'
  get 'vesselplanners/vessel_dispatch'
  post 'vesselplanners/vessel'
  get 'vesselplanners/vessel'
  get 'vesselplanners/new1'
  post 'vesselplanners/new1'
  post 'vesselplanners/new'
  get 'vesselplanners/new'
  get 'vesselplanners/dropdown'
  get 'vesselplanners/index1'
  post 'vesselplanners/index1'

  post 'feedback_report' => 'feedbacks#feedback_report'

  get 'utensils/fetch_utensil_category'

  get 'vesselplanners/index'
  get 'vesselplanners/details'
  get 'vesselplanners/utensilname'
  post 'vesselplanners/create'
  post 'vesselplanners/delete'
  get 'vesselplanners/tenantdetails'
  post 'vesselplanners/assigned_vessel'
  get  'vesselplanners/assigned_vessel'
  get 'vesselplanners/vessel_tenantdetail'
  get 'vesselplanners/edit'
  patch 'vesselplanners/update'



 # post 'vesselplanners/new'
  post 'audit_report' => 'auditreviews#audit_report'  

  get 'tenants/user_feedback'

  post 'menu_masters/menumaster_report'

  post 'menu_customers/csv_sheet'

  get 'daily_cook_sheet' => 'menu_customers#daily_cook_sheet'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  post 'feedbacks/feedback_update'
 
  post 'enrolments/enrol_delete_approval'

  post 'enrolments/newenrol_approval'

  get 'enrolments/approval_screen'

  post 'feedbacks/approval_feedback'
 
  get 'food_returns_report' => 'feedbacks#food_returns_report'

  post 'food_returns_report' => 'feedbacks#food_returns_report'

  get 'delivery_report' => 'dispatches#delivery_report'
  post 'delivery_report' => 'dispatches#delivery_report'

  get 'utensil_report' => 'utensils#utensil_report'
  #post 'utensil_report' => 'utensils#utensil_report'

  get 'customer_report' => 'tenants#customer_report'
  post 'customer_report' => 'tenants#customer_report'  

  get 'enrol_index' => 'enrolments#enrol_index'
  
  get 'attendance_index' => 'enrolments#attendance_index'
  get 'attendance' => 'enrolments#attendance'

  get 'point_of_sales/get_restriction'

  get 'kitchens/check_facilit_present'
  post 'kitchens/check_facilit_present'

  get 'tenant/check_meal_info'
  post 'tenant/check_meal_info'

  get 'point_of_sales/get_data'

  get 'point_of_sales/check_date'
  post 'point_of_sales/check_date'

  get 'meal_courses/check_position'
  post 'meal_courses/check_position'    

  get 'point_of_sales/check_tenant'
  post 'point_of_sales/check_tenant'

  get '/edit_item' => 'production_items#edit_item'
  patch '/update_item' => 'production_items#update_item'

  get 'unit_of_measurements/bck'

  get 'tenants/check_mg_present'
  post 'tenants/check_mg_present'

  get 'normalmenu_sites/menu_assign'

  get 'normalmenu_sites/menuplanner_design'

  get 'normalmenu_sites/menu_planner'

  get 'normalmenu_sites/wastage'
  post 'normalmenu_sites/wastage'

  get "kitchen_users/dynamic_drop"
  #post "kitchen_users/dynamic_drop"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get"check_tet/normalmenu_sites"
  post"check_tet/normalmenu_sites"
  get "kitchen_users/login"
  post "kitchen_users/login_validation"
  get 'kitchen_users/logout'
  get "kitchens/index"
  post "kitchens/create"
  get "kitchens/chef"

  get "food_groups/image_pop"
  get "customer_view_controls/billing_pop"
  get "customer_view_controls/nutrition_pop"
  get "/status" =>"normalmenu_sites#order_status"
  post "/status" =>"normalmenu_sites#order_status"
  get "/summaries" =>"normalmenu_sites#summary"
  post "/summaries" =>"normalmenu_sites#summary"
  get "/enrolled" =>"normalmenu_sites#enrolled"
  post "/enrolled" =>"normalmenu_sites#enrolled"
  get "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  post "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  get "/delivery_status" =>"normalmenu_sites#delivery_status"
  post "/delivery_status" =>"normalmenu_sites#delivery_status"

  get "normalmenu_sites/delivery_problem_status"
  post "normalmenu_sites/delivery_problem_status"

  get "/utensil_status" =>"normalmenu_sites#utensil_status"
  post "/utensil_status" =>"normalmenu_sites#utensil_status"
  get "enrolments/enrolment_upload"
  post "enrolments/enrolment_upload"
  get "enrolments/upload_process"
  post "enrolments/upload_process"
  get "normalmenu_sites/dashboard"
  post "normalmenu_sites/dashboard"
  get "normalmenu_sites/summary_edit"
  post "normalmenu_sites/summary_edit"
  get "normalmenu_sites/drop"
  get "normalmenu_sites/dropdown1"

  get "normalmenu_sites/normalmenu_category_add"
  #post "normalmenu_sites/normalmenu_category_add"
  post "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenu_category_edit"
  #post "normalmenu_sites/normalmenu_category_edit"
  post "normalmenu_sites/normalmenu_category_edit_save"
  get "normalmenu_sites/normalmenu_category_show"
  get "normalmenu_sites/normalmenu_category_delete"
  #post "normalmenu_sites/normalmenu_category_delete"
  get "normalmenu_sites/notreceive_status"

  get "enrolments/individual"

  get "feedbacks/allow_update"
  post "feedbacks/allow_update"

  get 'software_setups/check_username_present'
  post 'software_setups/check_username_present'

  get 'dispatch_utensils_mappings/rec'
  post 'dispatch_utensils_mappings/rec'

  resources :standards
  resources :item_meal_restrictions
  resources :menu_customers
  resources :menu_production_items
  resources :menu_masters
  resources :meal_restrictions
  resources :item_meal_courses
  resources :meal_courses
  resources :auditreviews
  resources :feedbacks
  resources :point_of_sales
  resources :kitchens
  resources :customer_view_controls
  resources :parent_orders
  resources :software_setups
  resources :dispatch_utensils_mappings
  resources :utensils_count_mappings
  resources :utensils_categories
  resources :payments
  resources :normalmenu_sites
  resources :normal_menus
  resources :operations
  resources :production_items
  resources :production_categories
  resources :item_subcategories
  resources :unit_of_measurements
  resources :nutritions
  resources :software_setup
  resources :food_groups
  resources :food_categories
  resources :item_categories
  resources :categories
  resources :tenants
  resources :dispatches
  resources :utensils
  resources :site_categories
  resources :enrolments
  resources :page_configurations
  resources :pages
  resources :tenant_details
  resources :users
  resources :kitchen_users
  resources :alleries
  
end

app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  before_action :set_enrolment, only: [:show, :edit, :update, :destroy]

  # GET /enrolments
  # GET /enrolments.json
  def index
    @enrolments = Enrolment.where(tenant_id: params[:format],is_active: true, status: "Approved")
  end

  def enrol_index
    #@tenants = Enrolment.all.group_by(&:tenant_id)
    @tenants = Enrolment.where(is_active: true, status: "Approved").group_by(&:tenant_id)
    @enrolments = Enrolment.all
  end

  def individual
    @enrolments = Enrolment.all      
  end

  def attendance
    @attendances = Attendance.where(:tenant_id => params[:format], :date => Date.today).order('enrolment_id ASC')
  end

  def attendance_index
    #@attendances = Attendance.where(:date => Date.today, attendance_log: true).group_by(&:tenant_id)
    @tenants = Tenant.where("from_date <= ? AND to_date >= ?", Date.today, Date.today).where(active: true)
  end

  # GET /enrolments/1
  # GET /enrolments/1.json
  def show
  end

  # GET /enrolments/new
  def new
    @enrolment = Enrolment.new
  end

  # GET /enrolments/1/edit
  def edit
  end

  def enrolment_upload
    @enrolment=Enrolment.new
  end

  def upload_process
    #file = params[:enrolment][:file1]
    #filename = file.original_filename
    enrolment = Enrolment.upload(params)

    if enrolment.class == Array and enrolment.count == 6

      if enrolment[2].present? and enrolment[3].present? and enrolment[4].present? and enrolment[5].present?
        flash[:notice] = "#{enrolment[0]} values has been successfully imported !!. #{enrolment[1]} values not saved!!. Standard #{enrolment[2]} is not in contract !!. Meal Time #{enrolment[3]} is not in contract !! Meal Restriction #{enrolment[4]} is not in contract !! . Meal Time #{enrolment[3]} is not in contract !! Student type #{enrolment[5]} is not in contract !! " 
      elsif enrolment[2].empty? and enrolment[3].empty? and enrolment[5].present?      
        flash[:notice] = "#{enrolment[0]} values has been successfully imported !!. #{enrolment[1]} values not saved!! Student Type #{enrolment[5]} is not in contract !! "

      elsif enrolment[2].empty? and enrolment[3].present?
        flash[:notice] = "#{enrolment[0]} values has been successfully imported !!. #{enrolment[1]} values not saved!! Meal Time #{enrolment[3]} is not in contract !! "
      elsif enrolment[2].present? and enrolment[3].empty?
        flash[:notice] = "#{enrolment[0]} values has been successfully imported !!. #{enrolment[1]} values not saved!! Standard #{enrolment[2]} is not in contract !! "
      elsif enrolment[2].empty? and enrolment[3].empty? 

        flash[:notice] = "#{enrolment[0]} values has been successfully imported !!. #{enrolment[1]} values not saved!!"
      elsif  enrolment[4]==0
        flash[:notice] = "#{enrolment[4]} values not imported !!. #{enrolment[1]} values not saved!! ..Meal Restriction #{enrolment[4]} is not in contract !!"
      end

    elsif enrolment.class == String      
      flash[:notice] = "#{enrolment}"
    else
      flash[:notice] = "Please try again!!"
    end
    redirect_to :action=> "enrol_index"

=begin
    if @enrolment == "File Invalid"
      flash[:notice] = "File Invalid"
      redirect_to :action=> "index"
    elsif @enrolment == "File Invalidddd"
      flash[:notice] = "Invalid Header Format!"
      redirect_to :action=> "index"
    elsif @enrolment == "meal_restriction is nill"
      flash[:notice] = "Meal Restriction column is must"
      redirect_to :action=> "index"
    elsif @enrolment == "c"
      flash[:notice] = "All Fields are Required"
      redirect_to :action=> "index"
    elsif @enrolment.present? &&  @enrolment.first.kind_of?(Integer) && @enrolment.last.empty?
      flash[:notice] = "#{@enrolment.first} Value Already Exists"
      redirect_to :action=> "index"
    elsif @enrolment.present? &&  @enrolment.first.nil? && @enrolment.last.present?
      flash[:notice] = "Your File Has been Successfully Imported."
      redirect_to :action=> "index"
    elsif @enrolment.present? &&  @enrolment.first.kind_of?(Integer) && @enrolment.last.present?
      tcount = @enrolment.last.count
      flash[:notice] = "#{tcount} values has been successfully imported. #{@enrolment.first} values already exists"
      redirect_to :action=> "index"
    else
      flash[:notice] = "Data Invalid"
      redirect_to :action=> "index"
    end
=end

  end

  # POST /enrolments
  # POST /enrolments.json
  def create
    @enrolment = Enrolment.new(enrolment_params)
    respond_to do |format|
      if @enrolment.save
        format.html { redirect_to @enrolment, notice: 'Enrolment was successfully created.' }
        format.json { render :show, status: :created, location: @enrolment }
      else
        format.html { render :new }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolments/1
  # PATCH/PUT /enrolments/1.json
  def update
    respond_to do |format|
      if @enrolment.update(enrolment_params)
        format.html { redirect_to @enrolment, notice: 'Enrolment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrolment }
      else
        format.html { render :edit }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolments/1
  # DELETE /enrolments/1.json
  def destroy
    @enrolment.destroy
    respond_to do |format|
      format.html { redirect_to enrolments_url, notice: 'Enrolment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approval_screen
    @approval_enrolment=Enrolment.where(is_active:false,status:"WaitingForApproval")
    @delete_enrolment=Enrolment.where(is_active:true ,status:"WaitingForApproval")
  end

  def newenrol_approval
    if params["commit"] == "Approve"
      Enrolment.where(id: params[:approval_id]).update(is_active: true, status: "Approved")
      enrolment = Enrolment.Tenant_update_details(params)
      if enrolment.class == Array 
         flash[:notice] = "#{enrolment[0]} #{enrolment[1]}"
       else
         flash[:notice] = "#{enrolment}"

      end
    elsif params["commit"] == "Reject"
      Enrolment.where(id: params[:approval_id]).destroy_all
      flash[:notice]="Enrolment Rejected"
    end
    redirect_to action: "approval_screen"    
  end

  def enrol_delete_approval
    if params["commit"] == "Approve"
        Enrolment.where(id: params[:approval_id]).update(is_active: false, status: "Approved").map{|i| i.destroy}
    elsif params["commit"] == "Reject"
         Enrolment.where(id: params[:approval_id]).update(is_active: true, status: "Rejected")
    end
    redirect_to action: "approval_screen"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrolment
      unless params[:id] == "undefined"
        @enrolment = Enrolment.find(params[:id])
      else
        redirect_to action: "index"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrolment_params
      params.require(:enrolment).permit(:name, :age_type, :date_of_birth, :height, :weight, :bmi, :standard, :id_number, :meal_plan, :meal_time, :food_category_id, :from_date, :to_date, :enrolment_type, :payment, :tenant_id, :user_id)
    end

end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/views/enrolments/_new.html.erb
<div class="modal-dialog">

    <div class="modal-header">
   
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    
    	<h4 class="modal-title">New Enrolment</h4>
  
  	</div>
  
  	<div class="modal-content">      
    
    	<div class="modal-body">
	
			<%= render 'form', enrolment: @enrolment %>      
    
    	</div>
  
  	</div>

</div>

app/views/enrolments/attendance.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="/assets/datatable.js"></script>
<script src="/assets/datahtml5button.js"></script>
<script src="/assets/jszip.js"></script>
<script src="/assets/datatablebutton.js"></script>
<link href="/assets/dataTable.css" rel="stylesheet">
<link href="/assets/datatablebutton.css" rel="stylesheet">

<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container">
    <div class="col-md-12">
      <div class="container">
        <div class="body-header">
          <div class="row">
            <div class="col-md-8">
              <h3 style="font-size: large;color: darkgreen;font-family: initial;">Attendance - <%= Tenant.find(params[:format]).name %> - <%= Date.today.strftime('%a, %d-%b-%Y') %></h3>
            </div>
            <div class="col-md-4">
              <%= link_to "Back", attendance_index_path, class: "btn btn-info" %>
            </div>
          </div>           
        </div>
      </div>      
    </div>  
  </div>  
    
  <div class="body-content">
    <div id="dashboard-container">
      <div class="table-container">
        <table class="table table-striped table-bordered table-hover display" cellspacing="0" width="100%" id="attendance">
          <thead>
            <tr>
              <th>Customer</th>
              <th>Name</th>
              <th>Student Id</th>
              <th>Sex</th>
              <th>Age type</th>              
              <th>Standard</th>
              <th>Meal Time</th>
              <th>Meal Type</th>
              <th>Meal Restriction</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @attendances.each do |attendance| %>      
              <tr id='<%= attendance.enrolment_id %>'>
                <td><%= attendance.tenant.name.titleize %></td>
                <td><%= attendance.enrolment.name.titleize %></td>
                <td><%= attendance.identity_number %></td>
                <td><%= attendance.enrolment.sex.titleize %></td>
                <td><%= attendance.age_type.titleize %></td>
                <td><%= attendance.standard %></td>                
                <td><%= attendance.meal_time.titleize %></td>
                <td><%= attendance.food_category.name.titleize %></td>
                <td><%= attendance.enrolment.meal_restriction.present? ? attendance.enrolment.meal_restriction.meal_restriction_name.titleize : "-" %></td>
                <% if attendance.attendance_log == true %>
                  <td style="color: green;">Present</td>
                <% else %>
                  <td style="color: red;">Absent</td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- <div class="side-pop" style="color:white;display:none;">
          <ul>
            <li><a title="Show" id="show" > <i class="btn btn-sm btn-default fa fa-sm fa-eye"></i></a></li>  
          </ul>
        </div> -->
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/enrolments/attendance_index.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container">
    <div class="body-header">
      <h3 style="font-size: x-large;color: darkgreen;font-family: initial;">Tenant wise Attendance - <span> <%= Date.today.strftime('%a, %d-%b-%Y') %></span></h3>
    </div> 
    
  <div class="body-content">
    <div id="dashboard-container">
      <div class="table-container">
        <table class="table table-striped table-bordered table-hover display" cellspacing="0" width="100%" id="enrolment">
          <thead>
            <tr>
              <th>Customer</th>
              <th>Meal Time</th>
              <th>Meal Restriction</th>
              <th>Enrolled</th>
              <th>Not Enrolled</th>
              <th>Parent Order</th>
              <th>Total Count</th>
              <th>Actual Consumed</th>
              <th>Actual Not Consumed</th>
              <!-- <th>Breakfast (Present / Enrolled)</th>
              <th>Lunch (Present / Enrolled)</th>
              <th>Dinner (Present / Enrolled)</th>
              <th>Total (Present / Enrolled)</th> -->
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @tenants.each do |tenant| %>
              <% tenant.tenant_details.group_by{|e| [e.meal_time, e.meal_restriction_id]}.map do |k, v| %>
                <% attendances = Attendance.where(date: Date.today, tenant_id: tenant.id, meal_time: k[0]) %>
                <tr>
                  <td><%= tenant.name %></td>
                  <td><%= k[0] %></td>
                  <td><%= k[1].present? ? MealRestriction.find(k[1]).meal_restriction_name : "Normal" %></td>
                  <% enroll = v.select { |e| e.order == "Enroll" }.pluck(:quantity).sum %>
                  <%# not_enroll = v.select { |e| e.order == "Not-Enroll" }.pluck(:quantity).sum %>
                  <% not_enroll = PointOfSale.where(tenant_id: tenant.id, date: Date.today, meal_time: k[0], meal_restriction_id: k[1]).pluck(:quantity).sum %>
                  <% parent_orders = ParentOrder.where(tenant_id: tenant.id, date: Date.today, meal_time: k[0], meal_restriction_id: k[1]).count %>
                  <td><%= enroll != 0 ? enroll : "" %></td>
                  <td><%= not_enroll != 0 ? not_enroll : "" %></td>
                  <td><%= parent_orders == 0 ? "" : parent_orders %></td>
                  <% menu_customer = MenuCustomer.find_by(tenant_id: tenant.id, date: Date.today, category_id: Category.find_by_category_name(k[0]), meal_restriction_id: k[1]) %>
                  <td><%= menu_customer.present? ? packs = menu_customer.packs_to_send : "" %></td>
                  <% present_count = attendances.select { |e| e.attendance_log == true and e.enrolment.meal_restriction_id == k[1] }.count %>
                  <%# absent_count = attendances.select { |e| e.attendance_log == false }.count %>
                  <td><%= present_count == 0 ? "" : present_count %></td>
                  <td><%#= absent_count == 0  ? "" : absent_count %><%= (packs.present? and present_count != 0) ? packs - present_count : "" %></td>

                  <!-- <td><%#= a = attendance.select{|i| i.meal_time == "Breakfast" }.count %> / <%#= aa = enrolments.select{|e| e.meal_time == "Breakfast" }.count %></td>
                  
                  <td><%#= b = attendance.select{|i| i.meal_time == "Lunch"}.count %> / <%#= bb = enrolments.select{|e| e.meal_time == "Lunch"}.count %></td>
                  
                  <td><%#= c = attendance.select{|i| i.meal_time == "Dinner"}.count %> / <%#= cc = enrolments.select{|e| e.meal_time == "Dinner"}.count %></td>
                  
                  <td><%#= a+b+c %> / <%#= aa+bb+cc %></td> -->


                  <td><%= link_to "View", attendance_path(tenant.id), style: "color: cadetblue;font-size: large;" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>        
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="clearfix"></div>
 </div>
</div>  

app/views/enrolments/edit.html.erb
<h1>Editing Enrolment</h1>

<%= render 'form', enrolment: @enrolment %>

<%= link_to 'Show', @enrolment %> |
<%= link_to 'Back', enrolments_path %>

app/views/enrolments/edit.js.erb
$("#editenrol-modal").html("<%= escape_javascript(render 'edit') %>")
$("#editenrol-modal").on('shown.bs.modal', function() {
  $('form').enableClientSideValidations();
}).modal("show")

app/views/enrolments/enrol_index.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container">
    <div class="col-md-12">
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <% value.split(".").map do |val| %>            
              <%= val %><br>
            <% end %>
            <button type="button" class="close" data-dismiss="alert"> &times; </button>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-6">
            <div class="body-header">
              <h3>CRM <span></span></h3>
              <h2>Enrolment List - <span> <button type="button" class="btn btn-primary btn-sm rounded-s" data-toggle="modal" data-target="#myModal"> Enrolment Count</button></span></h2>              
            </div>
          </div>
          <div class="col-md-6">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal1">Import Student Details</button>
          </div>
        </div>
      </div>        
    </div>  
  </div>
    
  <div class="body-content">
    <div id="dashboard-container">
      <div class="table-container">
        <table class="table table-striped table-bordered table-hover display" cellspacing="0" width="100%" id="enrolment">
          <thead>
            <tr>
              <th>Customer</th>
              <th>Enroll Count</th>
              <th>Not-Enroll Count</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @tenants.map do |tenant, enrolments| %>      
              <tr id='<%= tenant %>'>
                <td><%= Tenant.find(tenant).name.titleize if Tenant.find(tenant).present? %></td>
                <td><%= Enrolment.where(is_active: true,status: "Approved", order_source: "Enroll").count%></td>
                <td><%= Enrolment.where(is_active: true,status: "Approved", order_source: "Not Enrolled").count%></td>
                <td><%= link_to "View", enrolments_path(tenant) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- <div class="side-pop" style="color:white;display:none;">
          <ul>
            <li><a title="Show" id="show" > <i class="btn btn-sm btn-default fa fa-sm fa-eye"></i></a></li>  
          </ul>
        </div> -->
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="clearfix"></div>
</div>

<div class="container">
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Customer Details</h4>        
        </div>
        <div class="modal-body">
          <% ten_id = Enrolment.pluck(:tenant_id).uniq %>
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <th>Customer Name</th>
              <th>Meal Time</th>
              <th>Total Count</th>
            </thead>
            <tbody> 
              <% ten_id.map do |ii| %>
                <% tendata = Enrolment.where(tenant_id:ten_id,is_active: true, status: "Approved") %>
                <% mealtime = tendata.pluck(:meal_time).uniq %>
                <% mealtime.map do|jj| %>
                  <tr>  
                    <td><%= Tenant.find(ii).name %></td>  
                    <td><%= jj %></td>    
                    <td><%= count = Enrolment.where(tenant_id:ii,meal_time:jj, is_active: true, status: "Approved").count %></td>
                  </tr>              
                <% end %>
              <% end %>
            </tbody>  
          </table>
        </div>          
        <div class="modal-footer">          
          <button type="button" class="btn btn-danger btn-sm rounded-s" data-dismiss="modal">Close</button>        
        </div>                
      </div>      
    </div>          
  </div>  
</div>

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
<div class="container">
  <div class="modal-dialog" role="dialog">
    <div class="modal-content">
      <div class="modal-header">
        <center><h4 class="modal-title" id="exampleModalLabel">Import Students for a Tenant</h4></center>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for Enrolment.new,:url=> {:controller=>"enrolments", :action=>"upload_process"} do |f| %>
        <div class="modal-body">
          <div class="col-md-6">
            <%= f.collection_select :tenant_id, Tenant.all, :id, :name, {prompt: "Select a tenant"}, {required: true, class: "single tenant"} %>
          </div>
          <div class="col-md-6">
            Select File : <%= f.file_field :file1, accept: 'text/csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', required: true, class: "btn btn-default btn-file" %>
            <%= f.submit "Upload", :class=>"btn btn-primary" %>
          </div>
        </div>
        <div class="modal-footer">          
          <label class="btn btn-secondary" data-dismiss="modal">Cancel</label>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".single").select2();
  });

//  $(document).ready(function() {
 //   $(".tenant").change(function() {
  //    if ($(".tenant").val() != "") {
  //      $(".file").show();
   //   }
   //   else{
    //    $(".file").hide();
   //   }
  //  });
 // }); 

</script>

<style type="text/css">
  .modal-content1 {
    /*background: #7eb835 !important;*/
    height: 300px;
    margin-top: 130px;"
  }

  .modal-dialog1 {
    font-size: initial;
    font-family: unset;
  }
</style>
