config/routes.rb
Rails.application.routes.draw do

  resources :utensilnames
  resources :depriciation_categories
  resources :departments
  root :to => "kitchen_users#login"
  get 'vesselplanners/dispatched'
  post 'vesselplanners/dispatched' 
  get 'vesselplanners/dropdown1'
  get 'vesselplanners/vessel_dispatch'
  post 'vesselplanners/vessel'
  get 'vesselplanners/vessel'
  get 'vesselplanners/new1'
  post 'vesselplanners/new1'
  post 'vesselplanners/new'
  get 'vesselplanners/new'
  get 'vesselplanners/dropdown'
  get 'vesselplanners/index1'
  post 'vesselplanners/index1'

  post 'feedback_report' => 'feedbacks#feedback_report'

  get 'utensils/fetch_utensil_category'

  get 'vesselplanners/index'
  get 'vesselplanners/details'
  get 'vesselplanners/utensilname'
  post 'vesselplanners/create'
  post 'vesselplanners/delete'
  get 'vesselplanners/tenantdetails'
  post 'vesselplanners/assigned_vessel'
  get  'vesselplanners/assigned_vessel'
  get 'vesselplanners/vessel_tenantdetail'
  get 'vesselplanners/edit'
  patch 'vesselplanners/update'



 # post 'vesselplanners/new'
  post 'audit_report' => 'auditreviews#audit_report'  

  get 'tenants/user_feedback'

  post 'menu_masters/menumaster_report'

  post 'menu_customers/csv_sheet'

  get 'daily_cook_sheet' => 'menu_customers#daily_cook_sheet'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  post 'feedbacks/feedback_update'
 
  post 'enrolments/enrol_delete_approval'

  post 'enrolments/newenrol_approval'

  get 'enrolments/approval_screen'

  post 'feedbacks/approval_feedback'
 
  get 'food_returns_report' => 'feedbacks#food_returns_report'

  post 'food_returns_report' => 'feedbacks#food_returns_report'

  get 'delivery_report' => 'dispatches#delivery_report'
  post 'delivery_report' => 'dispatches#delivery_report'

  get 'utensil_report' => 'utensils#utensil_report'
  #post 'utensil_report' => 'utensils#utensil_report'

  get 'customer_report' => 'tenants#customer_report'
  post 'customer_report' => 'tenants#customer_report'  

  get 'enrol_index' => 'enrolments#enrol_index'
  
  get 'attendance_index' => 'enrolments#attendance_index'
  get 'attendance' => 'enrolments#attendance'

  get 'point_of_sales/get_restriction'

  get 'kitchens/check_facilit_present'
  post 'kitchens/check_facilit_present'

  get 'tenant/check_meal_info'
  post 'tenant/check_meal_info'

  get 'point_of_sales/get_data'

  get 'point_of_sales/check_date'
  post 'point_of_sales/check_date'

  get 'meal_courses/check_position'
  post 'meal_courses/check_position'    

  get 'point_of_sales/check_tenant'
  post 'point_of_sales/check_tenant'

  get '/edit_item' => 'production_items#edit_item'
  patch '/update_item' => 'production_items#update_item'

  get 'unit_of_measurements/bck'

  get 'tenants/check_mg_present'
  post 'tenants/check_mg_present'

  get 'normalmenu_sites/menu_assign'

  get 'normalmenu_sites/menuplanner_design'

  get 'normalmenu_sites/menu_planner'

  get 'normalmenu_sites/wastage'
  post 'normalmenu_sites/wastage'

  get "kitchen_users/dynamic_drop"
  #post "kitchen_users/dynamic_drop"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get"check_tet/normalmenu_sites"
  post"check_tet/normalmenu_sites"
  get "kitchen_users/login"
  post "kitchen_users/login_validation"
  get 'kitchen_users/logout'
  get "kitchens/index"
  post "kitchens/create"
  get "kitchens/chef"

  get "food_groups/image_pop"
  get "customer_view_controls/billing_pop"
  get "customer_view_controls/nutrition_pop"
  get "/status" =>"normalmenu_sites#order_status"
  post "/status" =>"normalmenu_sites#order_status"
  get "/summaries" =>"normalmenu_sites#summary"
  post "/summaries" =>"normalmenu_sites#summary"
  get "/enrolled" =>"normalmenu_sites#enrolled"
  post "/enrolled" =>"normalmenu_sites#enrolled"
  get "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  post "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  get "/delivery_status" =>"normalmenu_sites#delivery_status"
  post "/delivery_status" =>"normalmenu_sites#delivery_status"

  get "normalmenu_sites/delivery_problem_status"
  post "normalmenu_sites/delivery_problem_status"

  get "/utensil_status" =>"normalmenu_sites#utensil_status"
  post "/utensil_status" =>"normalmenu_sites#utensil_status"
  get "enrolments/enrolment_upload"
  post "enrolments/enrolment_upload"
  get "enrolments/upload_process"
  post "enrolments/upload_process"
  get "normalmenu_sites/dashboard"
  post "normalmenu_sites/dashboard"
  get "normalmenu_sites/summary_edit"
  post "normalmenu_sites/summary_edit"
  get "normalmenu_sites/drop"
  get "normalmenu_sites/dropdown1"

  get "normalmenu_sites/normalmenu_category_add"
  #post "normalmenu_sites/normalmenu_category_add"
  post "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenu_category_edit"
  #post "normalmenu_sites/normalmenu_category_edit"
  post "normalmenu_sites/normalmenu_category_edit_save"
  get "normalmenu_sites/normalmenu_category_show"
  get "normalmenu_sites/normalmenu_category_delete"
  #post "normalmenu_sites/normalmenu_category_delete"
  get "normalmenu_sites/notreceive_status"

  get "enrolments/individual"

  get "feedbacks/allow_update"
  post "feedbacks/allow_update"

  get 'software_setups/check_username_present'
  post 'software_setups/check_username_present'

  get 'dispatch_utensils_mappings/rec'
  post 'dispatch_utensils_mappings/rec'

  resources :standards
  resources :item_meal_restrictions
  resources :menu_customers
  resources :menu_production_items
  resources :menu_masters
  resources :meal_restrictions
  resources :item_meal_courses
  resources :meal_courses
  resources :auditreviews
  resources :feedbacks
  resources :point_of_sales
  resources :kitchens
  resources :customer_view_controls
  resources :parent_orders
  resources :software_setups
  resources :dispatch_utensils_mappings
  resources :utensils_count_mappings
  resources :utensils_categories
  resources :payments
  resources :normalmenu_sites
  resources :normal_menus
  resources :operations
  resources :production_items
  resources :production_categories
  resources :item_subcategories
  resources :unit_of_measurements
  resources :nutritions
  resources :software_setup
  resources :food_groups
  resources :food_categories
  resources :item_categories
  resources :categories
  resources :tenants
  resources :dispatches
  resources :utensils
  resources :site_categories
  resources :enrolments
  resources :page_configurations
  resources :pages
  resources :tenant_details
  resources :users
  resources :kitchen_users
  resources :alleries
  
end

app/models/production_category.rb
class ProductionCategory < ApplicationRecord
	validates :name, presence: true,uniqueness: { case_sensitive: false}
	acts_as_paranoid
	#has_many :production_items, dependent: :destroy
end

app/controllers/production_categories_controller.rb
class ProductionCategoriesController < ApplicationController
  before_action :set_production_category, only: [:show, :edit, :update, :destroy]

  # GET /production_categories
  # GET /production_categories.json
  def index
    @production_categories = ProductionCategory.all
  end

  # GET /production_categories/1
  # GET /production_categories/1.json
  def show
  end

  # GET /production_categories/new
  def new
    @production_category = ProductionCategory.new
  end

  # GET /production_categories/1/edit
  def edit
  end

  # POST /production_categories
  # POST /production_categories.json
  def create
    @production_category = ProductionCategory.new(production_category_params)

    respond_to do |format|
      if @production_category.save
        @production_category.update(:created_by=>session[:kitchen_user_id])
        format.html { redirect_to action: "index", notice: 'Production category was successfully created.' }
        format.json { render :show, status: :created, location: @production_category }
      else
        format.html { render :new }
        format.json { render json: @production_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /production_categories/1
  # PATCH/PUT /production_categories/1.json
  def update
    respond_to do |format|
      if @production_category.update(production_category_params)
        @production_category.update(:updated_by=>session[:kitchen_user_id])
        format.html { redirect_to action: "index", notice: 'Production category was successfully updated.' }
        format.json { render :show, status: :ok, location: @production_category }
      else
        format.html { render :edit }
        format.json { render json: @production_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /production_categories/1
  # DELETE /production_categories/1.json
  def destroy
    @production_category.destroy
    respond_to do |format|
      format.html { redirect_to production_categories_url, notice: 'Production category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production_category
      @production_category = ProductionCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_category_params
      #params.fetch(:production_category, {})
      params.require(:production_category).permit(:name, :description)
      
    end
end

app/helpers/production_categories_helper.rb
module ProductionCategoriesHelper
end

app/views/production_categories/_form.html.erb
<!--%= link_to 'New Operation', new_operation_path %-->
<%= form_for(production_category,validate: true) do |f| %>
  <!--% if production_category.errors.any? %>
    <div id="error_explanation">
      <h2><!%= pluralize(production_category.errors.count, "error") %> prohibited this production_category from being saved:</h2>

      <ul>
      <!% production_category.errors.full_messages.each do |message| %>
        <li><!%= message %></li>
      <!% end %>
      </ul>
    </div>
  <!% end %-->
  <article class="content item-editor-page wrap-center">
    <div class="title-block">
        <h3 class="title"><span class="sparkline bar" data-type="bar"></span> </h3>
    </div>
    <form name="item">
            <div class="row">
                <div class="form-group">
                <div class="col-xs-4">
                <label class="control-label">
                 <%= f.label :name ,"Name"%>
                 </label><div class="form-group"> 
                 <%= f.text_field :name,required:true,class: "form-control boxed " %>
                 </div>
                 </div>
                 </div>
                 </div>

                 <div class="row">
                <div class="form-group">
                 <div class="col-xs-4">
                <label class="control-label">
                 <%= f.label :description %>
                 </label><div class="form-group"> 
                 <%= f.text_area :description,class: "form-control boxed " %>
                 </div>
                 </div>
             </div>
        </div>
        
        
        <div class="row">
            <div class="col col-md-3"><%= link_to "Back", production_categories_path ,:class=>"btn btn-primary"%></div>
            <div class="col col-md-3"><%= f.submit "Submit",:class=>"btn btn-primary"%></div>
        </div>
        

        <!-- <div class="form-group row mrgn-top">
            <div class="col-sm-10 col-sm-offset-4"> <%= f.submit "submit",:class=>"btn btn-primary"%></div>
       </div> -->
  </form>
  </article>
<% end %>

app/views/production_categories/edit.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container"> 
  <div class="body-header">  
    	<h3 class="modal-title">Edit - Production Category </h3>
 	</div>
 	  
	  		<%= render 'form', production_category: @production_category %>
  	</div>

</div>

app/views/production_categories/edit.js.erb
$("#editproduction_category-modal").html("<%= escape_javascript(render 'edit') %>")
$("#editproduction_category-modal").on('shown.bs.modal', function() {
  $('form').enableClientSideValidations();
}).modal("show")


$( ".dropdown" ).select2({
});

app/views/production_categories/index.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container">
    <div class="body-header">
      <h3>Master<span><%= link_to 'New Production Category', new_production_category_path, :class=>"btn btn-primary btn-sm rounded-s"%> </span></h3>
      <h2>Production Category</h2>
    </div>
    <div class="body-content">
      <div id="dashboard-container">
        <div class="table-container">
          <table class="table table-striped table-bordered table-hover display" cellspacing="0" width="100%" id="production_category">
            <thead>
               <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Created_by</th>
                  <th>Updated_by</th>
                  <th>Edit</th>
                  <!-- <th>Delete</th> -->
                </tr>
            </thead>
            <tbody>
              <% @production_categories.each do |production_category| %>
      <tr>
        <td><%= production_category.name%></td>
        <td><%= production_category.description%></td>
        <td><%= create(production_category) %></td>
        <td><%= update(production_category) %></td>
       <!--  <td><!%= link_to 'Show', production_category %></td> -->
        <td><%= link_to '', edit_production_category_path(production_category),:class=>"fa fa-pencil" %></td>
        <!-- <td><%#= link_to '', production_category, method: :delete, data: { confirm: 'Are you sure?' },:class=>"fa fa-trash-o" %></td> -->
      </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
  

app/views/production_categories/new.html.erb
<div class="col-md-12 col-sm-8 body-wrap">
  <div class="body-container"> 
  <div class="body-header">   
    	<h3 class="modal-title">Add - Production Category </h3>
  </div>
	  
	  		<%= render 'form', production_category: @production_category %>
</div>
</div>

app/views/production_categories/new.js.erb
$("#newproduction_category-modal").html("<%= escape_javascript(render 'new') %>")
$("#newproduction_category-modal").on('shown.bs.modal', function() {
  $('form').enableClientSideValidations();
}).modal("show")



app/views/production_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_production_category_path(@production_category) %> |
<%= link_to 'Back', production_categories_path %>