config/routes.rb
Rails.application.routes.draw do

  resources :utensilnames
  resources :depriciation_categories
  resources :departments
  root :to => "kitchen_users#login"
  get 'vesselplanners/dispatched'
  post 'vesselplanners/dispatched' 
  get 'vesselplanners/dropdown1'
  get 'vesselplanners/vessel_dispatch'
  post 'vesselplanners/vessel'
  get 'vesselplanners/vessel'
  get 'vesselplanners/new1'
  post 'vesselplanners/new1'
  post 'vesselplanners/new'
  get 'vesselplanners/new'
  get 'vesselplanners/dropdown'
  get 'vesselplanners/index1'
  post 'vesselplanners/index1'

  post 'feedback_report' => 'feedbacks#feedback_report'

  get 'utensils/fetch_utensil_category'

  get 'vesselplanners/index'
  get 'vesselplanners/details'
  get 'vesselplanners/utensilname'
  post 'vesselplanners/create'
  post 'vesselplanners/delete'
  get 'vesselplanners/tenantdetails'
  post 'vesselplanners/assigned_vessel'
  get  'vesselplanners/assigned_vessel'
  get 'vesselplanners/vessel_tenantdetail'
  get 'vesselplanners/edit'
  patch 'vesselplanners/update'



 # post 'vesselplanners/new'
  post 'audit_report' => 'auditreviews#audit_report'  

  get 'tenants/user_feedback'

  post 'menu_masters/menumaster_report'

  post 'menu_customers/csv_sheet'

  get 'daily_cook_sheet' => 'menu_customers#daily_cook_sheet'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  post 'feedbacks/feedback_update'
 
  post 'enrolments/enrol_delete_approval'

  post 'enrolments/newenrol_approval'

  get 'enrolments/approval_screen'

  post 'feedbacks/approval_feedback'
 
  get 'food_returns_report' => 'feedbacks#food_returns_report'

  post 'food_returns_report' => 'feedbacks#food_returns_report'

  get 'delivery_report' => 'dispatches#delivery_report'
  post 'delivery_report' => 'dispatches#delivery_report'

  get 'utensil_report' => 'utensils#utensil_report'
  #post 'utensil_report' => 'utensils#utensil_report'

  get 'customer_report' => 'tenants#customer_report'
  post 'customer_report' => 'tenants#customer_report'  

  get 'enrol_index' => 'enrolments#enrol_index'
  
  get 'attendance_index' => 'enrolments#attendance_index'
  get 'attendance' => 'enrolments#attendance'

  get 'point_of_sales/get_restriction'

  get 'kitchens/check_facilit_present'
  post 'kitchens/check_facilit_present'

  get 'tenant/check_meal_info'
  post 'tenant/check_meal_info'

  get 'point_of_sales/get_data'

  get 'point_of_sales/check_date'
  post 'point_of_sales/check_date'

  get 'meal_courses/check_position'
  post 'meal_courses/check_position'    

  get 'point_of_sales/check_tenant'
  post 'point_of_sales/check_tenant'

  get '/edit_item' => 'production_items#edit_item'
  patch '/update_item' => 'production_items#update_item'

  get 'unit_of_measurements/bck'

  get 'tenants/check_mg_present'
  post 'tenants/check_mg_present'

  get 'normalmenu_sites/menu_assign'

  get 'normalmenu_sites/menuplanner_design'

  get 'normalmenu_sites/menu_planner'

  get 'normalmenu_sites/wastage'
  post 'normalmenu_sites/wastage'

  get "kitchen_users/dynamic_drop"
  #post "kitchen_users/dynamic_drop"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get"check_tet/normalmenu_sites"
  post"check_tet/normalmenu_sites"
  get "kitchen_users/login"
  post "kitchen_users/login_validation"
  get 'kitchen_users/logout'
  get "kitchens/index"
  post "kitchens/create"
  get "kitchens/chef"

  get "food_groups/image_pop"
  get "customer_view_controls/billing_pop"
  get "customer_view_controls/nutrition_pop"
  get "/status" =>"normalmenu_sites#order_status"
  post "/status" =>"normalmenu_sites#order_status"
  get "/summaries" =>"normalmenu_sites#summary"
  post "/summaries" =>"normalmenu_sites#summary"
  get "/enrolled" =>"normalmenu_sites#enrolled"
  post "/enrolled" =>"normalmenu_sites#enrolled"
  get "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  post "/dispatch_status" =>"normalmenu_sites#dispatch_status"
  get "/delivery_status" =>"normalmenu_sites#delivery_status"
  post "/delivery_status" =>"normalmenu_sites#delivery_status"

  get "normalmenu_sites/delivery_problem_status"
  post "normalmenu_sites/delivery_problem_status"

  get "/utensil_status" =>"normalmenu_sites#utensil_status"
  post "/utensil_status" =>"normalmenu_sites#utensil_status"
  get "enrolments/enrolment_upload"
  post "enrolments/enrolment_upload"
  get "enrolments/upload_process"
  post "enrolments/upload_process"
  get "normalmenu_sites/dashboard"
  post "normalmenu_sites/dashboard"
  get "normalmenu_sites/summary_edit"
  post "normalmenu_sites/summary_edit"
  get "normalmenu_sites/drop"
  get "normalmenu_sites/dropdown1"

  get "normalmenu_sites/normalmenu_category_add"
  #post "normalmenu_sites/normalmenu_category_add"
  post "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenusite_save"
  get "normalmenu_sites/normalmenu_category_edit"
  #post "normalmenu_sites/normalmenu_category_edit"
  post "normalmenu_sites/normalmenu_category_edit_save"
  get "normalmenu_sites/normalmenu_category_show"
  get "normalmenu_sites/normalmenu_category_delete"
  #post "normalmenu_sites/normalmenu_category_delete"
  get "normalmenu_sites/notreceive_status"

  get "enrolments/individual"

  get "feedbacks/allow_update"
  post "feedbacks/allow_update"

  get 'software_setups/check_username_present'
  post 'software_setups/check_username_present'

  get 'dispatch_utensils_mappings/rec'
  post 'dispatch_utensils_mappings/rec'

  resources :standards
  resources :item_meal_restrictions
  resources :menu_customers
  resources :menu_production_items
  resources :menu_masters
  resources :meal_restrictions
  resources :item_meal_courses
  resources :meal_courses
  resources :auditreviews
  resources :feedbacks
  resources :point_of_sales
  resources :kitchens
  resources :customer_view_controls
  resources :parent_orders
  resources :software_setups
  resources :dispatch_utensils_mappings
  resources :utensils_count_mappings
  resources :utensils_categories
  resources :payments
  resources :normalmenu_sites
  resources :normal_menus
  resources :operations
  resources :production_items
  resources :production_categories
  resources :item_subcategories
  resources :unit_of_measurements
  resources :nutritions
  resources :software_setup
  resources :food_groups
  resources :food_categories
  resources :item_categories
  resources :categories
  resources :tenants
  resources :dispatches
  resources :utensils
  resources :site_categories
  resources :enrolments
  resources :page_configurations
  resources :pages
  resources :tenant_details
  resources :users
  resources :kitchen_users
  resources :alleries
  
end

app/models/operation.rb
class Operation < ApplicationRecord
	belongs_to :unit_of_measurement
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      #params.fetch(:operation, {})
      params.require(:operation).permit(:name, :time, :manpower, :process_cost, :unit_of_measurement_id, :quantity)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= link_to 'New Production Item', new_production_item_path %>
<%= form_for(operation) do |f| %>
  <% if operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
    <%= f.text_field :name,:class=>"form-control", :required=>"true" %><br>
<%= f.label :manpower %>
    <%= f.text_field :manpower,:class=>"form-control", :required=>"true" %><br>
<%= f.label :time %>
    <%= f.text_field :time,:class=>"form-control", :required=>"true" %><br>
<%= f.label :process_cost %>
    <%= f.text_field :process_cost,:class=>"form-control", :required=>"true" %><br>
    <%= f.label :quantity %>
    <%= f.text_field :quantity,:class=>"form-control", :required=>"true" %><br>
    <%= f.label :unit_of_measurement_id %>
    <%= f.collection_select :unit_of_measurement_id, UnitOfMeasurement.order(:name),:id,:name, include_blank: true, :required=>"true" %>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    <tr>
    <td>name</td><td>time</td>
      <td>manpower</td>
<td>process_cost</td>
 <td>unit_of_measurement</td>
<td>quantity</td>
</tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
      <td><%= operation.name%></td>
      <td><%= operation.time%></td>
      <td><%= operation.manpower%></td>
<td><%= operation.process_cost%></td>
 <td><%= UnitOfMeasurement.find(operation.unit_of_measurement_id).name%></td>
<td><%= operation.quantity%></td>
        <td><%= link_to 'Show', operation %></td>
        <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>